version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    profiles:
      - local

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    profiles:
      - local

  app:
    build: .
    ports:
      - "${APP_PORT:-8501}:8501"
    volumes:
      - .:/app
      - .data:/app/.data
    environment:
      - WAREHOUSE=${WAREHOUSE:-DUCKDB}
      - DUCKDB_PATH=${DUCKDB_PATH:-.data/local.duckdb}
      - LLM_PROVIDER=${LLM_PROVIDER:-ollama}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3.1}
      - VECTOR_BACKEND=${VECTOR_BACKEND:-chroma}
      - VECTOR_DIR=${VECTOR_DIR:-.data/vector}
    depends_on:
      - ollama
      - chromadb
    profiles:
      - app

volumes:
  ollama_data:
  chroma_data: