-- Snowflake setup script
-- Run this script in your Snowflake environment to set up the necessary objects

-- Create database (adjust name as needed)
CREATE DATABASE IF NOT EXISTS BI_ASSISTANT;
USE DATABASE BI_ASSISTANT;

-- Create schemas
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS MARTS;
CREATE SCHEMA IF NOT EXISTS SEEDS;

-- Create warehouse (adjust size as needed)
CREATE WAREHOUSE IF NOT EXISTS BI_ASSISTANT_WH
  WITH WAREHOUSE_SIZE = 'X-SMALL'
       AUTO_SUSPEND = 60
       AUTO_RESUME = TRUE
       INITIALLY_SUSPENDED = TRUE;

-- Create role for BI Assistant
CREATE ROLE IF NOT EXISTS BI_ASSISTANT_ROLE;

-- Grant permissions
GRANT USAGE ON WAREHOUSE BI_ASSISTANT_WH TO ROLE BI_ASSISTANT_ROLE;
GRANT USAGE ON DATABASE BI_ASSISTANT TO ROLE BI_ASSISTANT_ROLE;
GRANT ALL ON SCHEMA BI_ASSISTANT.STAGING TO ROLE BI_ASSISTANT_ROLE;
GRANT ALL ON SCHEMA BI_ASSISTANT.MARTS TO ROLE BI_ASSISTANT_ROLE;
GRANT ALL ON SCHEMA BI_ASSISTANT.SEEDS TO ROLE BI_ASSISTANT_ROLE;

-- Grant permissions on future objects
GRANT ALL ON FUTURE TABLES IN SCHEMA BI_ASSISTANT.STAGING TO ROLE BI_ASSISTANT_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA BI_ASSISTANT.STAGING TO ROLE BI_ASSISTANT_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA BI_ASSISTANT.MARTS TO ROLE BI_ASSISTANT_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA BI_ASSISTANT.MARTS TO ROLE BI_ASSISTANT_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA BI_ASSISTANT.SEEDS TO ROLE BI_ASSISTANT_ROLE;

-- Create user (replace with actual username)
-- CREATE USER IF NOT EXISTS BI_ASSISTANT_USER
--   PASSWORD = 'your_secure_password'
--   DEFAULT_ROLE = BI_ASSISTANT_ROLE
--   DEFAULT_WAREHOUSE = BI_ASSISTANT_WH
--   DEFAULT_NAMESPACE = BI_ASSISTANT.MARTS;

-- Grant role to user
-- GRANT ROLE BI_ASSISTANT_ROLE TO USER BI_ASSISTANT_USER;